<?php
/**
  * Implements hook_views_api().
  */
function vistamodulo_views_api() {
  return array(
    'api' => 3,
    );
}
/**
 * Implements hook_views_data()
 */
function vistamodulo_views_data() {
  dpm('mensaje');
  $data['vistamodulo']['table']['group'] = t('vistamodulo');
  $data['vistamodulo']['table']['base'] = array(
    'field' => 'nid',
    'title' => t('vistamodulo'),
    'help' => t("Example table contains example content and can be related to nodes."),
    'weight' => -10,
  );

  $data['vistamodulo']['table']['join'] = array(
    'node' => array(
      'left_field' => 'nid',
      'field' => 'nid',
    ),
  );
  $data['vistamodulo']['nid'] = array(
    'title' => t('Example content'),
    'help' => t('Some example content that references a node.'),
    'relationship' => array(
      'base' => 'node',
      'field' => 'nid',
      'handler' => 'views_handler_relationship',
      'label' => t('Example node'),
    ),
  );

  $data['vistamodulo']['plai_text_field'] = array(
    'title' => t('Plain text field'),
    'help' => t('Just a plain text field.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  $data['vistamodulo']['timestamp_field'] = array(
    'title' => t('Timestamp field'),
    'help' => t('Just a timestamp field.'),
    'field' => array(
      'handler' => 'views_handler_field_date',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort_date',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_date',
    ),
  );
  return $data;
}
