<?php

/**
 * @file
 * Module file for formulario
 */

/**
 * Implements hook_menu().
 *
 * Provide a menu item and a page to demonstrate features of this example
 * module.
 */
function formulario_menu() {
  $items['formulario/add'] = array(
    'title' => 'Departamentos de Colombia',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formulario_nameform'),
    'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['tablepage'] = array(
    'title' => 'Consulta Departamentos de Colombia',
    'page callback' => 'mytable_table_data', 'access arguments' => array("access content"),
    'type' => MENU_LOCAL_TASK,
  );
  $items['tablepage2'] = array('title' => 'Consulta Departamentos de Colombia',
    'page callback' => 'image_table_data',
    'access arguments' => array("access content"),
    'type' => MENU_LOCAL_TASK,
  );
  $items['formulario/edit/%'] = array(
    'title' => 'Departamentos de Colombia',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formulario_edit_nameform', 2),
    'access arguments' => array(2), 'access callback' => 'access_permiso',
    'type' => MENU_LOCAL_TASK,
  );
  $items['formulario/ver/%'] = array(
    'title' => 'Departamentos de Colombia',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formulario_ver_nameform', 2),
    'access arguments' => array(2),
    'access callback' => 'access_permiso',
    'type' => MENU_CALLBACK,
  );
  $items['formulario/delete/%'] = array(
    'title' => 'Departamentos de Colombia',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formulario_delete_nameform', 2),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );
  $items['formulario/deletem'] = array(
    'title' => 'Departamentos de Colombia',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formulario_deletemessage_nameform'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  $items['formulario/consulta'] = array(
    'title' => 'Consulta Departamentos de Colombia',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mytable_table_consulta_data'),
    'access arguments' => array("access content"),
    'type' => MENU_CALLBACK
  );
  $items['test'] = array(
    'title' => 'Consulta Departamentos de Colombia',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('testform'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementa la tabla que muestra los registros.
 */
function mytable_table_data() {
  $output = '';
  $header = array(
    array('data' => 'Codigo', 'field' => 'id_depto'),
    array('data' => 'Departamento', 'field' => 'depto_name'),
    array('data' => 'Capital', 'field' => 'cap_depto'),
    array('data' => 'Poblacion', 'field' => 'poblacion'),
    array('data' => 'Editar', 'field' => t('Edit')),
    array('data' => 'Borrar', 'field' => t('Delete')),
    array('data' => 'Ver', 'field' => t('Ver')),
    'thumbnail',
    );
    if (isset($_GET['sort']) && isset($_GET['order'])) {
      if ($_GET['sort'] == 'asc')
        $sort = 'ASC';
      else
      $sort = 'DESC';

    switch ($_GET['order']) {
      case 'id_depto':
      $order = 'id_depto';
      break;
      case 'depto_name':
      $order = 'depto_name';
      break;
      case 'depto_name':
      $order = 'cap_depto';
      break;
      case 'depto_name':
      $order = 'poblacion';
      break;
      default:
      $order = 'id_depto';
      }
  }
  else {
    $sort = 'ASC';
    $order = 'id_depto';
  }

  $query = db_select("crud_deptoscol", "n");
  $query->fields('n', array('id_depto', 'depto_name', 'cap_depto', 'poblacion'));
  $query->orderBy($order, $sort);
  $query->join('file_managed', 'f', 'f.fid = n.uid2');
  $query = $query->extend('TableSort')->extend('PagerDefault')->limit(2);
  $result = $query->fields('f', array('uri'))->execute();
  $rows=array();
  while ($data = $result->fetchObject()) {
    dpm($data);
    $rows[] = array($data->id_depto, $data->depto_name, $data->cap_depto, $data->poblacion,
      theme('image', array('path' => $data->uri, 'height' => 200)),
      l(t('Editar'), 'formulario/edit/' . $data->id_depto), l(t('Delete'), 'formulario/deletem/' . $data->id_depto),
      l(t('Ver'), 'formulario/ver/' . $data->id_depto));
    }
    $output = theme_table(
    array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'sticky' => TRUE,
      'caption' => '',
      'colgroups' => array(),
      'empty' => t("La tabla no tiene ninguna fila")
      )
    ) . theme('pager');
  return $output;
}

/**
 *  Definimos un formulario para agragar archivos
 */
function formulario_nameform() {
  $form['name'] = array(
    '#title' => t('Departamentos de Colombia'),
    '#type' => 'fieldset',
    '#description' => t('Los campos con * son obligatorios'),
  );
  $form['name']['id_depto'] = array(
    '#title' => 'Codigo Departamento',
    '#type' => 'textfield',
    '#element_validate' => array(t('_element_validate_number')),
    '#description' => t('Ingrese codigo'),
    '#required' => TRUE,
  );
  $form['name']['depto_name'] = array(
    '#title' => 'Nombre Departamento',
    '#type' => 'textfield',
    '#empty_option' => 'mi mensaje',
    '#description' => t('Departamento'),
    '#required' => TRUE,
  );
  $form['name']['name_cap'] = array(
    '#title' => 'Capital',
    '#type' => 'textfield',
    '#description' => t('Capital'),
    '#required' => TRUE,
  );
  $form['name']['poblacion'] = array(
    '#title' => 'Poblacion',
    '#type' => 'textfield',
    '#element_validate' => array('_element_validate_number'),
    '#description' => t('poblacion'),
    '#required' => TRUE,
  );
  $form['name']['file'] = array(
    '#type' => 'managed_file',
    '#title' => t('Image'),
    '#description' => t('Subir un archivo, extenciones permitidas: jpg, jpeg, png, gif'),
    '#upload_location' => 'public://personal/',
    '#upload_validators' => array(
    'file_validate_extensions' => array('gif png jpg jpeg'),
    ),
    '#required' => TRUE,
    );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Guardar'),
  );
  return $form;
}
/**
 *  Definimos el submit del formulario
 */
function formulario_nameform_submit($form, &$form_state) {
  $id = $form_state['values']['id_depto'];
  $depto = $form_state['values']['depto_name'];
  $capital = $form_state['values']['name_cap'];
  $pobla = $form_state['values']['poblacion'];
  $uid2 = $form_state['values']['file'];
/**
  *  Guardamos la imagen con status
  */
  unset($form_state['values']['file']);
  $retor = file_load($uid2);
  $retor->status = FILE_STATUS_PERMANENT;
  file_save($retor);
  drupal_set_message(t('formulario diligenciado, %id, %depto, %capital, %poblacion',
    array('%id' => $id, '%depto' => $depto, '%capital' => $capital, '%poblacion' => $pobla, '%uid2' => $uid2)));
/**
  * Inserat los datos en la DB.
  */
  $nid = db_insert('crud_deptoscol')
  ->fields(array(
  'id_depto' => $id,
  'depto_name' => $depto,
  'cap_depto' => $capital,
  'poblacion' => $pobla,
  'uid2' => $uid2,
  ))
  ->execute();
  drupal_set_message(t('registro guradado!'));
}
/**
  * Validate Departamento exist.
  */
function formulario_nameform_validate($form, &$form_state) {
  $result = db_select('crud_deptoscol', 'c')
  ->fields('c', array('depto_name'))
  ->condition('depto_name', $form_state['values']['depto_name'], '=')
  ->execute()
  ->fetchAssoc();
  if (($result['depto_name']) == ($form_state['values']['depto_name'])) {
    form_set_error('depto_name', t('El Departamento ya esta registrado'));
  }
}
/**
 * formulario para editar.
 */
function formulario_edit_nameform($form, &$form_state, $id_depto) {
  dpm($id_depto, 'id');

  $query = db_select('crud_deptoscol', 'n')
  ->fields('n', array('id_depto', 'depto_name', 'cap_depto', 'poblacion'))
  ->condition('id_depto', $id_depto, '=')
  ->execute()
  ->fetchObject();

  if ($query == '') {
    form_set_error('depto_name', t('El registro no existe'));
  }
  else{
    $form['name'] = array(
      '#title' => t('Departamentos de Colombia'),
      '#type' => 'fieldset',
      '#description' => t('Los campos con * son obligatorios'),
    );
    $form['name']['id_depto'] = array(
      '#type' => 'value',
      '#value' => $query->id_depto,
      '#default_value' => $query->id_depto,
    );
    $form['name']['depto_name'] = array(
      '#title' => t('Nombre Departamento'),
      '#type' => 'textfield',
      '#default_value' => $query->depto_name,
      '#description' => t('Ingrese su Apellido'),
      '#required' => TRUE,
    );
    $form['name']['name_cap'] = array(
      '#title' => t('Capital'),
      '#type' => 'textfield',
      '#default_value' => $query->cap_depto,
      '#description' => t('Capital'),
      '#required' => TRUE,
    );
    $form['name']['poblacion'] = array(
      '#title' => t('poblacion'),
      '#type' => 'textfield',
      '#default_value' => $query->poblacion,
      '#element_validate' => array('_element_validate_number'),
      '#description' => t('poblacion'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Guardar'),
    );
  }
  return $form;
}
/**
 * submit edit form.
 */
function formulario_edit_nameform_submit($form, &$form_state) {
  $id = $form_state['values']['id_depto'];
  $depto = $form_state['values']['depto_name'];
  $capital = $form_state['values']['name_cap'];
  $pobla = $form_state['values']['poblacion'];
  drupal_set_message(t('formulario diligenciado, %id, %depto, %capital, %poblacion',
  array('%id' => $id, '%depto' => $depto, '%capital' => $capital, '%poblacion' => $pobla)));

  $data = array(
    'id_depto' => $id,
    'depto_name' => $depto,
    'cap_depto' => $capital,
    'poblacion' => $pobla,
    );
  $num_updated = db_update('crud_deptoscol')
  ->fields($data)
  ->condition('id_depto', $id, '=')
  ->execute();
  drupal_set_message(t('Registro guradaddo!'));
  $form_state['redirect'] = 'tablepage';
}
/**
 * formulario mensaje confirmasion eliminar.
 */
function formulario_deletemessage_nameform($form, &$form_state, $id_depto) {
  $form['name'] = array(
    '#title' => t('Departamentos de Colombia'),
    '#type' => 'fieldset',
    '#description' => t('Esta seguro que desea continuar con la operacion'),
  );
  $form['name']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Eliminar'),
  );
  $form['name']['submit2'] = array(
    '#type' => 'submit',
    '#value' => t('Cancelar'),
    '#submit' => array('cancelar_del'),
  );
  $form['name']['oculto'] = array(
    '#type' => 'value',
    '#value' => $id_depto,
  );
  return $form;
}
/**
  * Funciones que redirecionan.
  */
function cancelar_del($form, &$form_state) {
  $form_state['redirect'] = 'tablepage';
}
function insertar_imagen($form, &$form_state) {
  $form_state['redirect'] = 'test';
}
/**
 * formulario submit eliminar.
 */
function formulario_deletemessage_nameform_submit($form, &$form_state) {
  $id_depto = $form_state['values']['oculto'];
  dpm($id_depto, 'id');
  $del_updated = db_delete('crud_deptoscol')
  ->condition('id_depto', $id_depto, '=')
  ->execute();
  drupal_set_message(t('Registro Borrado!'));
  $form_state['redirect'] = 'tablepage';
}
/**
 * formulario valida si el registro existe.
 */
function access_permiso($id_depto) {
  $query = db_select('crud_deptoscol', 'n')
  ->fields('n', array('id_depto', 'depto_name', 'cap_depto', 'poblacion'))
  ->condition('id_depto', $id_depto, '=')
  ->execute()
  ->fetchObject();

  if ($query != '') {
    return TRUE;
    }
  else {
    drupal_set_message(t('El registro no existe'), 'status', FALSE);
    return FALSE;
  }
}
/**
 * Formulario Buscar
 */
function mytable_table_consultaform_data($form, &$form_state) {
  $form['name'] = array(
    '#title' => t('Departamentos de Colombia'),
    '#type' => 'fieldset',
    );
  $form['name']['id_depto'] = array(
    '#title' => t('Codigo Departamento'),
    '#type' => 'textfield',
    '#description' => t('Ingrese codigo'),
    );
  $form['name']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Buscar'),
    );
  return $form;
}
/**
 * Buscar Formulario
 */
function mytable_table_consulta_data($form, &$form_state) {
  $output = '';
  $header = array(
    array('data' => 'Codigo', 'field' => 'id_depto'),
    array('data' => 'Departamento', 'field' => 'depto_name'),
    array('data' => 'Capital', 'field' => 'cap_depto'),
    array('data' => 'Poblacion', 'field' => 'poblacion'),
    array('data' => 'Editar', 'field' => t('Edit')),
    array('data' => 'Borrar', 'field' => t('Delete')),
    );

  if (isset($_GET['sort']) && isset($_GET['order'])) {
    if ($_GET['sort'] == 'asc')
      $sort = 'ASC';
    else
      $sort = 'DESC';

    switch ($_GET['order']) {
      case 'id_depto':
      $order = 'id_depto';
      break;
      case 'depto_name':
      $order = 'depto_name';
      break;
      case 'depto_name':
      $order = 'cap_depto';
      break;
      case 'depto_name':
      $order = 'poblacion';
      break;
      default:
      $order = 'id_depto';
      }
  }
  else {
    $sort = 'ASC';
    $order = 'id_depto';
  }

  $query = db_select("crud_deptoscol", "n");
  $query->fields('n', array('id_depto', 'depto_name', 'cap_depto', 'poblacion'));
  $query->orderBy($order, $sort);

  $query = $query->extend('TableSort')->extend('PagerDefault')->limit(2);
  $result = $query->execute();
  $rows=array();
  while ($data = $result->fetchObject()) {
    $rows[] = array($data->id_depto, $data->depto_name, $data->cap_depto, $data->poblacion, l(t('Editar'), 'formulario/edit/' . $data->id_depto), l(t('Delete'), 'formulario/deletem/' . $data->id_depto));
    }
  $output = theme_table(
    array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'sticky' => TRUE,
      'caption' => '',
      'colgroups' => array(),
      'empty' => t("La tabla no tiene ninguna fila")
    )
  ) . theme('pager');

  $cadena['contenido'] = array(
    'dto1' => mytable_table_consultaform_data($form, $form_state),
    'dto2' => array('#markup' => $output, ),
  );
  return $cadena;
}
/**
 * Load Image
 */
function formulario_ver_nameform($form, &$form_state, $id_depto) {
  dpm($id_depto, 'id');
  $query = db_select('crud_deptoscol', 'n')
  ->fields('n', array('id_depto', 'depto_name', 'cap_depto', 'poblacion', 'uid2'))
  ->condition('id_depto', $id_depto, '=')
  ->execute()
  ->fetchObject();

  $file_image = file_load($query->uid2);
  $imagen = theme('image', array('path' => $file_image->uri, 'height' => 200));
  if ($query == '') {
    form_set_error('depto_name', t('El registro no existe'));
  }
  else {
    $form['picture'] = array(
      '#title' => t('Departamentos de Colombia'),
      '#markup' =>  $imagen ,
    );
    $form['name']['picture2'] = array(
      '#title' => t('Codigo Departamento'),
      '#type' => 'textfield',
      '#default_value' => $query->uid2,
      '#disabled' => TRUE,
      '#size' => 10,
    );
    $form['name'] = array(
      '#title' => t('Departamentos de Colombia'),
      '#type' => 'fieldset',
    );
    $form['name']['id_depto'] = array(
      '#title' => t('Codigo Departamento'),
      '#type' => 'textfield',
      '#default_value' => $query->id_depto,
      '#disabled' => TRUE,
      '#size' => 10,
    );
    $form['name']['depto_name'] = array(
      '#title' => t('Nombre Departamento'),
      '#type' => 'textfield',
      '#default_value' => $query->depto_name,
      '#disabled' => TRUE,
      '#size' => 30,
    );
    $form['name']['name_cap'] = array(
      '#title' => t('Capital'),
      '#type' => 'textfield',
      '#disabled' => TRUE,
      '#default_value' => $query->cap_depto,
      '#size' => 30,
    );
    $form['name']['poblacion'] = array(
      '#title' => t('Poblacion'),
      '#type' => 'textfield',
      '#default_value' => $query->poblacion,
      '#disabled' => TRUE,
      '#size' => 30,
    );
    $form['name']['submit2'] = array(
      '#type' => 'submit',
      '#value' => t('Volver'),
      '#submit' => array('cancelar_del'),
    );
  }
  return $form;
}
/**
 * Load Image
 */
function image_table_data() {
  $output = '';
  $header = array(
    array('data' => 'Codigo', 'field' => 'fid'),
    array('data' => 'uid', 'field' => 'uid'),
    array('data' => 'filename', 'field' => 'filename'),
    array('data' => 'uri', 'field' => 'uri'),
    array('data' => 'filemime', 'field' => 'filemime'),
    array('data' => 'filesize', 'field' => 'filesize'),
    array('data' => 'status', 'field' => 'status'),
    'thumbnail',
    array('data' => 'Ver', 'field' => t('Ver')),
    );

  if (isset($_GET['sort']) && isset($_GET['order'])) {
    if ($_GET['sort'] == 'asc')
      $sort = 'ASC';
    else
      $sort = 'DESC';
    switch ($_GET['order']) {
      case 'fid':
      $order = 'fid';
      break;
      case 'uid':
      $order = 'uid';
      break;
      case 'filename':
      $order = 'filename';
      break;
      case 'uri':
      $order = 'uri';
      break;
      case 'filemime':
      $order = 'filemime';
      break;
      case 'filesize':
      $order = 'filesize';
      break;
      case 'status':
      $order = 'status';
      break;
      default:
      $order = 'fid';
    }
  }
  else {
    $sort = 'ASC';
    $order = 'fid';
  }

  $query = db_select("file_managed", "n");
  $query->fields('n', array('fid', 'uid', 'filename', 'uri', 'filemime', 'filesize', 'status'));
  $query->orderBy($order, $sort);
  $query = $query->extend('TableSort')->extend('PagerDefault')->limit(10);
  $result = $query->execute();
  $rows=array();
  while ($data = $result->fetchObject()) {
    $rows[] = array($data->fid, $data->uid, $data->filename,
      $data->uri, $data->filemime, $data->filesize,
      $data->status,
      theme('image_style', array('style_name' => '300x300', 'path' => $data->uri)),
      l(t('Ver'), 'formulario/ver/' . $data->fid));
  }
  $output = theme_table(
    array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'sticky' => TRUE,
      'caption' => '',
      'colgroups' => array(),
      'empty' => t("La tabla no tiene ninguna fila")
    )
  ) . theme('pager');

  return $output;
}
